### ISSUE TITLE
type ProgramTrace should be called Configuration

### ISSUE THREAD

**Issue by albertolluch** [team-checkr/fsharp-starter#4]
type ProgramTrace, declared here:

https://github.com/team-checkr/fsharp-starter/blob/6fcbc67d03656aa673de1a1149456910568ad485/Interpreter.fs#L24

does not represent a program trace but a program configuration

A trace is a list of program configurations.

**Comment by oeb25** [comment]
Yes! I think the entire output format of the interpreter should be revised.

## Input

```fs
type InterpreterMemory =
    { variables: Map<string, int>
      arrays: Map<string, List<int>> }

type Input =
    { determinism: Determinism
      assignment: InterpreterMemory
      trace_size: int }
```

Overall, I think the input is fine, apart from maybe `trace_size`? Maybe `trace_length`, or `configuration_count`, `steps`, `steps_to_produce`, `required_steps`, `max_steps`? Suggestions are welcome.

## Output

Currently it looks like this:

```fs
type ProgramState = Running | Stuck | Terminated

type ProgramTrace = { node: string; state: ProgramState; memory: InterpreterMemory }

type Output = List<ProgramTrace>
```

Having the `ProgramState` at each configuration is kind of pointless. I would suggest something like the following:

```fs
type TerminationState = Running | Stuck | Terminated

type Configuration = { node: string; memory: InterpreterMemory }

type Output = { steps: List<Configuration>; final: TerminationState }
```

One problem I see with this, is that `node` is typed as string. So if they want to reuse the `Configuration` type for not only the output, then they need to somehow cope with having `node` be a string or convert between their internal `Node` type and the string during execution, both of which are sub-optimal.

In principle we could have `Configuration` be generic over the node type, or let the students change the node type. Perhaps something like this:

```fs
// TODO: Change this to you internal version of node
// If your node type is defined in graph, consider using the following:
// type Node = Graph.Node
type Node = string

type TerminationState = Running | Stuck | Terminated

type Configuration<'node> = { node: 'node; memory: InterpreterMemory }

type Output = { steps: List<Configuration<string>>; final: TerminationState }

let stringifyNode (internalNode: Node): string =
    // TODO: implement for internal node type
    internalNode

let prepareConfiguration (c: Configuration<Node>): Configuration<string> =
    { node = stringifyNode c.node; memory = c.memory }

// ... rest of the code ...

let analysis (src: string) (input: Input) : Output =
    failwith "Interpreter not yet implemented" // TODO: start here
    let steps: List<Configuration<Node>> = failwith "TODO"
    let final: TerminationState = failwith "TODO"
    { steps = List.map prepareConfiguration steps; final = final }
```

This would allow them to use their internal node type, while still confirming to a serializable format in the end.

**Comment by albertolluch** [comment]
> Overall, I think the input is fine, apart from maybe `trace_size`? Maybe `trace_length`, or `configuration_count`, `steps`, `steps_to_produce`, `required_steps`, `max_steps`? Suggestions are welcome.

I prefer length over size. The book uses the terminology "execution steps". 

Also, instead of "traces" the book uses "execution sequence", but trace is just fine.

> Having the `ProgramState` at each configuration is kind of pointless.

I agree.

 I would suggest something like the following:
> 
> ```fsharp
> type TerminationState = Running | Stuck | Terminated
> 
> type Configuration = { node: string; memory: InterpreterMemory }
> 
> type Output = { steps: List<Configuration>; final: TerminationState }

I agree. For coherence with the book "steps" could be called "execution_sequence".

> One problem I see with this, is that `node` is typed as string. So if they want to reuse the `Configuration` type for not only the output, then they need to somehow cope with having `node` be a string or convert between their internal `Node` type and the string during execution, both of which are sub-optimal.
> 
> In principle we could have `Configuration` be generic over the node type, or let the students change the node type. Perhaps something like this:
> 
> ```fsharp
> // TODO: Change this to you internal version of node
> // If your node type is defined in graph, consider using the following:
> // type Node = Graph.Node
> type Node = string
> 
> type TerminationState = Running | Stuck | Terminated
> 
> type Configuration<'node> = { node: 'node; memory: InterpreterMemory }
> 
> type Output = { steps: List<Configuration<string>>; final: TerminationState }
> 
> let stringifyNode (internalNode: Node): string =
>     // TODO: implement for internal node type
>     internalNode
> 
> let prepareConfiguration (c: Configuration<Node>): Configuration<string> =
>     { node = stringifyNode c.node; memory = c.memory }
> 
> // ... rest of the code ...
> 
> let analysis (src: string) (input: Input) : Output =
>     failwith "Interpreter not yet implemented" // TODO: start here
>     let steps: List<Configuration<Node>> = failwith "TODO"
>     let final: TerminationState = failwith "TODO"
>     { steps = List.map prepareConfiguration steps; final = final }
> ```
> 
> This would allow them to use their internal node type, while still confirming to a serializable format in the end.

I see. I don't have a strong preference for this one.
